# <span style="color:red"> QTM 151 - Practice Quiz </span>

<font size="5"> 

Print your name below

In [1]:
# Write your answer here
print("Jiuyi (Joy) Cheng")

Jiuyi (Joy) Cheng

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should work as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [2]:
# Write your answer here:
print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "5">

Import pandas

In [3]:
import pandas as pd


<font size = "5">

(1) Replace the values of a column

<font size = "3">

- Consider the DataFrame ``df_movies`` created below.
- In the "country" column, change the values "American" and "Korean" to "USA" and "ROK" respectively
- Do this by using the ``.replace`` method.

In [4]:
# Create example DataFrame - **don't change this**
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"]
country = ["American", "American", "France", "Korean", "Thailand", "Korean", "France",
    "France", "Japan", "Italy", "American"]
runtime = [106, 119, 108, 120, 97, 115, 96, 91, 88, 98, 120]
year = [2023, 1941, 2017, 2017, 2004, 2003, 1967, 1964, 1977, 1977, 1986]
movie_dict = {"title" : titles, "country" : country, "runtime" : runtime, "year" : year}
df_movies = pd.DataFrame(movie_dict)

# your answer here
df_movies['country'] = df_movies['country'].replace({'American': 'USA', 'Korean': 'ROK'})

display(df_movies["country"].value_counts())

country
USA         3
France      3
ROK         2
Thailand    1
Japan       1
Italy       1
Name: count, dtype: int64

<font size = "5">

(2) Recode a numeric column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories:

$\qquad$ ``` ["1941-1967","1968-1999","2000-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [5]:
# your code here
df_movies['year_brackets'] = pd.cut(
    df_movies['year'],
    bins=[1940, 1967, 1999, 2024],
    labels=["1941-1967","1968-1999","2000-onwards"])

display(df_movies.head())

          title   country  runtime  year year_brackets
0    Past Lives       USA      106  2023  2000-onwards
1  Citizen Kane       USA      119  1941     1941-1967
2       Revenge    France      108  2017  2000-onwards
3          Okja       ROK      120  2017  2000-onwards
4       Shutter  Thailand       97  2004  2000-onwards

<font size = "5">

(3) Rename column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Rename the column "runtime" to "runtime(minutes)"

In [6]:
# Write your answer here:
# Rename the column "runtime" to "runtime(minutes)"
df_movies = df_movies.rename(columns={"runtime": "runtime(minutes)"})
display(df_movies.head())

          title   country  runtime(minutes)  year year_brackets
0    Past Lives       USA               106  2023  2000-onwards
1  Citizen Kane       USA               119  1941     1941-1967
2       Revenge    France               108  2017  2000-onwards
3          Okja       ROK               120  2017  2000-onwards
4       Shutter  Thailand                97  2004  2000-onwards

<font size = "5">

(4) Merge dataset

<font size = "3">

- Consider the DataFrames ``df_movies`` (created above) and ``df_scores`` (created below)
- Create a new dataset using  ```pd.merge()``` using <br>
"df_movies" as the primary dataset, and <br>
"df_scores" as the secondary dataset, <br>
merging on the column "title"
- You should **ONLY** merge the "imdb_score" column <br>
from the secondary dataset (not the "director" column)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging

In [7]:
# create example DataFrame - don't change this
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"]
scores = [7.8, 8.2, 6.4, 7.3, 7.0, 7.1, 6.9, 7.8, 7.2, 7.3, 7.7]
directors = ["Celine Song", "Orson Welles", "Coralie Fargeat", "Bong Joon Ho", 
    "Banjong Pisanthanakun", "Kim Jee-woon", "Jean-Luc Godard", "Jacques Demy", 
    "Nobuhiko Obayashi", "Dario Argento", "David Lynch"]

movie_dict2 = {"title" : titles, "imdb_score" : scores, "director" : directors}
df_scores = pd.DataFrame(movie_dict2)

# Write your answer here:

df_merged = pd.merge(
    df_movies,
    df_scores[['title', 'imdb_score']],
    on='title',
    how='left')

display(df_merged.head())

          title   country  runtime(minutes)  year year_brackets  imdb_score
0    Past Lives       USA               106  2023  2000-onwards         7.8
1  Citizen Kane       USA               119  1941     1941-1967         8.2
2       Revenge    France               108  2017  2000-onwards         6.4
3          Okja       ROK               120  2017  2000-onwards         7.3
4       Shutter  Thailand                97  2004  2000-onwards         7.0

<font size = "5">

(5) Aggregate and sort

<font size = "3">

- Using the merged dataset you created above, do the following in a single line by chaining:
    - Group the dataset by "country"
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score
    - Score by average IMBD score in **descending order**

Print the resulting DataFrame

In [8]:
# Write your answer here:

df_grouped = df_merged.groupby('country').agg(
    avg_runtime = ('runtime(minutes)', 'mean'),
    max_runtime = ('runtime(minutes)', 'max'),
    avg_imdb_score = ('imdb_score', 'mean'),
    min_imdb_score = ('imdb_score', 'min')
).sort_values(by='avg_imdb_score', ascending=False) 

display(df_grouped)

          avg_runtime  max_runtime  avg_imdb_score  min_imdb_score
country
USA        115.000000          120        7.900000             7.7
Italy       98.000000           98        7.300000             7.3
Japan       88.000000           88        7.200000             7.2
ROK        117.500000          120        7.200000             7.1
France      98.333333          108        7.033333             6.4
Thailand    97.000000           97        7.000000             7.0

<font size = "5">

(6) Query and Aggregate

<font size = "3">

Using the merged dataset you created above, do the following in a single line by chaining:

- Subset the observations for 'country == France' using ```.query()```
- Sort the values by year (oldest first)
- Extract the two oldest movies

Print the resulting DataFrame to the screen

In [9]:
# Write your answer here:
df_france_oldest = df_merged.query("country == 'France'").sort_values(by='year', ascending=True).head(2) # Extract the two oldest movies

display(df_france_oldest)

,title,country,runtime(minutes),year,year_brackets,imdb_score
7,The Umbrellas of Cherbourg,France,91,1964,1941-1967,7.8
6,La Chinoise,France,96,1967,1941-1967,6.9